import { RESPONSIBILITY_GROUPS } from "./roles.js";

export const PERMISSIONS = {
  STAFF_VIEW: "staff.view",
  STAFF_CREATE: "staff.create",
  STAFF_UPDATE: "staff.update",
  STAFF_DEACTIVATE: "staff.deactivate",
  STAFF_MANAGE_PERMISSIONS: "staff.managePermissions",

  PRODUCTS_VIEW: "products.view",
  PRODUCTS_CREATE: "products.create",
  PRODUCTS_UPDATE: "products.update",
  PRODUCTS_UPDATE_PRICE: "products.updatePrice",

  STOCK_VIEW: "stock.view",
  STOCK_RECEIVE: "stock.receive",
  STOCK_ADJUST: "stock.adjust",
  STOCK_COUNT: "stock.count",
  STOCK_MARK_DAMAGED: "stock.markDamaged",
  STOCK_MARK_MISSING: "stock.markMissing",

  SALES_CREATE: "sales.create",
  SALES_DISCOUNT: "sales.discount",
  SALES_CANCEL: "sales.cancel",

  CUSTOMERS_VIEW: "customers.view",
  CUSTOMERS_CREATE: "customers.create",
  CUSTOMERS_UPDATE: "customers.update",

  DEBTS_CREATE: "debts.create",
  DEBTS_RECORD_PAYMENT: "debts.recordPayment",
  DEBTS_WRITE_OFF: "debts.writeOff",

  CASH_RECEIVE_PAYMENT: "cash.receivePayment",
  CASH_CLOSE_DAY: "cash.closeDay",
  CASH_VIEW_DIFFERENCE: "cash.viewDifference",

  EXPENSES_CREATE: "expenses.create",
  EXPENSES_APPROVE: "expenses.approve",

  REPORTS_VIEW_SALES: "reports.viewSales",
  REPORTS_VIEW_PROFIT: "reports.viewProfit",
  REPORTS_VIEW_STOCK: "reports.viewStock",
  REPORTS_VIEW_DEBTS: "reports.viewDebts",

  APPROVALS_REVIEW: "approvals.review",
  SETTINGS_UPDATE: "settings.update",
  AUDIT_LOGS_VIEW: "auditLogs.view",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const RESPONSIBILITY_GROUP_PERMISSIONS = {
  [RESPONSIBILITY_GROUPS.ADMIN_HELPER]: [
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.AUDIT_LOGS_VIEW,
  ],

  [RESPONSIBILITY_GROUPS.MANAGER]: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_UPDATE,
    PERMISSIONS.DEBTS_CREATE,
    PERMISSIONS.DEBTS_RECORD_PAYMENT,
    PERMISSIONS.CASH_VIEW_DIFFERENCE,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.REPORTS_VIEW_SALES,
    PERMISSIONS.REPORTS_VIEW_STOCK,
    PERMISSIONS.REPORTS_VIEW_DEBTS,
  ],

  [RESPONSIBILITY_GROUPS.SELLER]: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_UPDATE,
    PERMISSIONS.DEBTS_CREATE,
  ],

  [RESPONSIBILITY_GROUPS.CASHIER]: [
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.CASH_RECEIVE_PAYMENT,
    PERMISSIONS.CASH_CLOSE_DAY,
    PERMISSIONS.CASH_VIEW_DIFFERENCE,
    PERMISSIONS.DEBTS_RECORD_PAYMENT,
  ],

  [RESPONSIBILITY_GROUPS.STOREKEEPER]: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.STOCK_RECEIVE,
    PERMISSIONS.STOCK_COUNT,
    PERMISSIONS.STOCK_MARK_DAMAGED,
    PERMISSIONS.STOCK_MARK_MISSING,
  ],
} as const;
